spring:
  application:
    name: spring-boot-mvc-rest
  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: api-docs.yaml
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: info
